#pragma once

#include <cstdint>

#include <GL3/gl3.h>

namespace Twil {
namespace Platform {

class SymbolLoaderT;

}
}

namespace Twil {
namespace Gl {
namespace Context {

void initialize(Platform::SymbolLoaderT const &);

}
}
}

// We define our functions in a namespace and immediately use it so we dont conflict with libGL
namespace Twil {
namespace Gl {
namespace Procs {

void glCullFace(std::uint32_t);
void glFrontFace(std::uint32_t);
void glHint(std::uint32_t, std::uint32_t);
void glLineWidth(float);
void glPointSize(float);
void glPolygonMode(std::uint32_t, std::uint32_t);
void glScissor(std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glTexParameterf(std::uint32_t, std::uint32_t, float);
void glTexParameterfv(std::uint32_t, std::uint32_t, float const *);
void glTexParameteri(std::uint32_t, std::uint32_t, std::int32_t);
void glTexParameteriv(std::uint32_t, std::uint32_t, std::int32_t const *);
void glTexImage1D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::uint32_t, void const *);
void glTexImage2D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::uint32_t, void const *);
void glDrawBuffer(std::uint32_t);
void glClear(std::uint32_t);
void glClearColor(float, float, float, float);
void glClearStencil(std::int32_t);
void glClearDepth(double);
void glStencilMask(std::uint32_t);
void glColorMask(std::uint8_t, std::uint8_t, std::uint8_t, std::uint8_t);
void glDepthMask(std::uint8_t);
void glDisable(std::uint32_t);
void glEnable(std::uint32_t);
void glFinish(void);
void glFlush(void);
void glBlendFunc(std::uint32_t, std::uint32_t);
void glLogicOp(std::uint32_t);
void glStencilFunc(std::uint32_t, std::int32_t, std::uint32_t);
void glStencilOp(std::uint32_t, std::uint32_t, std::uint32_t);
void glDepthFunc(std::uint32_t);
void glPixelStoref(std::uint32_t, float);
void glPixelStorei(std::uint32_t, std::int32_t);
void glReadBuffer(std::uint32_t);
void glReadPixels(std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::uint32_t, void *);
void glGetBooleanv(std::uint32_t, std::uint8_t *);
void glGetDoublev(std::uint32_t, double *);
std::uint32_t glGetError(void);
void glGetFloatv(std::uint32_t, float *);
void glGetIntegerv(std::uint32_t, std::int32_t *);
std::uint8_t const * glGetString(std::uint32_t);
void glGetTexImage(std::uint32_t, std::int32_t, std::uint32_t, std::uint32_t, void *);
void glGetTexParameterfv(std::uint32_t, std::uint32_t, float *);
void glGetTexParameteriv(std::uint32_t, std::uint32_t, std::int32_t *);
void glGetTexLevelParameterfv(std::uint32_t, std::int32_t, std::uint32_t, float *);
void glGetTexLevelParameteriv(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t *);
std::uint8_t glIsEnabled(std::uint32_t);
void glDepthRange(double, double);
void glViewport(std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glDrawArrays(std::uint32_t, std::int32_t, std::int32_t);
void glDrawElements(std::uint32_t, std::int32_t, std::uint32_t, void const *);
void glGetPointerv(std::uint32_t, void * *);
void glPolygonOffset(float, float);
void glCopyTexImage1D(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glCopyTexImage2D(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glCopyTexSubImage1D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glCopyTexSubImage2D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glTexSubImage1D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::uint32_t, void const *);
void glTexSubImage2D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::uint32_t, void const *);
void glBindTexture(std::uint32_t, std::uint32_t);
void glDeleteTextures(std::int32_t, std::uint32_t const *);
void glGenTextures(std::int32_t, std::uint32_t *);
std::uint8_t glIsTexture(std::uint32_t);
void glBlendColor(float, float, float, float);
void glBlendEquation(std::uint32_t);
void glDrawRangeElements(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, std::uint32_t, void const *);
void glTexImage3D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::uint32_t, void const *);
void glTexSubImage3D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::uint32_t, void const *);
void glCopyTexSubImage3D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glActiveTexture(std::uint32_t);
void glSampleCoverage(float, std::uint8_t);
void glCompressedTexImage3D(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, void const *);
void glCompressedTexImage2D(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, void const *);
void glCompressedTexImage1D(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, std::int32_t, std::int32_t, void const *);
void glCompressedTexSubImage3D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::int32_t, void const *);
void glCompressedTexSubImage2D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::int32_t, void const *);
void glCompressedTexSubImage1D(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::int32_t, void const *);
void glGetCompressedTexImage(std::uint32_t, std::int32_t, void *);
void glBlendFuncSeparate(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t);
void glMultiDrawArrays(std::uint32_t, std::int32_t const *, std::int32_t const *, std::int32_t);
void glMultiDrawElements(std::uint32_t, std::int32_t const *, std::uint32_t, void const * *, std::int32_t);
void glPointParameterf(std::uint32_t, float);
void glPointParameterfv(std::uint32_t, float const *);
void glPointParameteri(std::uint32_t, std::int32_t);
void glPointParameteriv(std::uint32_t, std::int32_t const *);
void glGenQueries(std::int32_t, std::uint32_t *);
void glDeleteQueries(std::int32_t, std::uint32_t const *);
std::uint8_t glIsQuery(std::uint32_t);
void glBeginQuery(std::uint32_t, std::uint32_t);
void glEndQuery(std::uint32_t);
void glGetQueryiv(std::uint32_t, std::uint32_t, std::int32_t *);
void glGetQueryObjectiv(std::uint32_t, std::uint32_t, std::int32_t *);
void glGetQueryObjectuiv(std::uint32_t, std::uint32_t, std::uint32_t *);
void glVertexAttribP1ui(std::uint32_t, std::uint32_t, std::uint8_t, std::uint32_t);
void glVertexAttribP1uiv(std::uint32_t, std::uint32_t, std::uint8_t, std::uint32_t const *);
void glVertexAttribP2ui(std::uint32_t, std::uint32_t, std::uint8_t, std::uint32_t);
void glVertexAttribP2uiv(std::uint32_t, std::uint32_t, std::uint8_t, std::uint32_t const *);
void glVertexAttribP3ui(std::uint32_t, std::uint32_t, std::uint8_t, std::uint32_t);
void glVertexAttribP3uiv(std::uint32_t, std::uint32_t, std::uint8_t, std::uint32_t const *);
void glVertexAttribP4ui(std::uint32_t, std::uint32_t, std::uint8_t, std::uint32_t);
void glVertexAttribP4uiv(std::uint32_t, std::uint32_t, std::uint8_t, std::uint32_t const *);
void glBindBuffer(std::uint32_t, std::uint32_t);
void glDeleteBuffers(std::int32_t, std::uint32_t const *);
void glGenBuffers(std::int32_t, std::uint32_t *);
std::uint8_t glIsBuffer(std::uint32_t);
void glBufferData(std::uint32_t, std::ptrdiff_t, void const *, std::uint32_t);
void glBufferSubData(std::uint32_t, std::ptrdiff_t, std::ptrdiff_t, void const *);
void glGetBufferSubData(std::uint32_t, std::ptrdiff_t, std::ptrdiff_t, void *);
void * glMapBuffer(std::uint32_t, std::uint32_t);
std::uint8_t glUnmapBuffer(std::uint32_t);
void glGetBufferParameteriv(std::uint32_t, std::uint32_t, std::int32_t *);
void glGetBufferPointerv(std::uint32_t, std::uint32_t, void * *);
void glBlendEquationSeparate(std::uint32_t, std::uint32_t);
void glDrawBuffers(std::int32_t, std::uint32_t const *);
void glStencilOpSeparate(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t);
void glStencilFuncSeparate(std::uint32_t, std::uint32_t, std::int32_t, std::uint32_t);
void glStencilMaskSeparate(std::uint32_t, std::uint32_t);
void glAttachShader(std::uint32_t, std::uint32_t);
void glBindAttribLocation(std::uint32_t, std::uint32_t, char const *);
void glCompileShader(std::uint32_t);
std::uint32_t glCreateProgram(void);
std::uint32_t glCreateShader(std::uint32_t);
void glDeleteProgram(std::uint32_t);
void glDeleteShader(std::uint32_t);
void glDetachShader(std::uint32_t, std::uint32_t);
void glDisableVertexAttribArray(std::uint32_t);
void glEnableVertexAttribArray(std::uint32_t);
void glGetActiveAttrib(std::uint32_t, std::uint32_t, std::int32_t, std::int32_t *, std::int32_t *, std::uint32_t *, char *);
void glGetActiveUniform(std::uint32_t, std::uint32_t, std::int32_t, std::int32_t *, std::int32_t *, std::uint32_t *, char *);
void glGetAttachedShaders(std::uint32_t, std::int32_t, std::int32_t *, std::uint32_t *);
std::int32_t glGetAttribLocation(std::uint32_t, char const *);
void glGetProgramiv(std::uint32_t, std::uint32_t, std::int32_t *);
void glGetProgramInfoLog(std::uint32_t, std::int32_t, std::int32_t *, char *);
void glGetShaderiv(std::uint32_t, std::uint32_t, std::int32_t *);
void glGetShaderInfoLog(std::uint32_t, std::int32_t, std::int32_t *, char *);
void glGetShaderSource(std::uint32_t, std::int32_t, std::int32_t *, char *);
std::int32_t glGetUniformLocation(std::uint32_t, char const *);
void glGetUniformfv(std::uint32_t, std::int32_t, float *);
void glGetUniformiv(std::uint32_t, std::int32_t, std::int32_t *);
void glGetVertexAttribdv(std::uint32_t, std::uint32_t, double *);
void glGetVertexAttribfv(std::uint32_t, std::uint32_t, float *);
void glGetVertexAttribiv(std::uint32_t, std::uint32_t, std::int32_t *);
void glGetVertexAttribPointerv(std::uint32_t, std::uint32_t, void * *);
std::uint8_t glIsProgram(std::uint32_t);
std::uint8_t glIsShader(std::uint32_t);
void glLinkProgram(std::uint32_t);
void glShaderSource(std::uint32_t, std::int32_t, char const * *, std::int32_t const *);
void glUseProgram(std::uint32_t);
void glUniform1f(std::int32_t, float);
void glUniform2f(std::int32_t, float, float);
void glUniform3f(std::int32_t, float, float, float);
void glUniform4f(std::int32_t, float, float, float, float);
void glUniform1i(std::int32_t, std::int32_t);
void glUniform2i(std::int32_t, std::int32_t, std::int32_t);
void glUniform3i(std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glUniform4i(std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glUniform1fv(std::int32_t, std::int32_t, float const *);
void glUniform2fv(std::int32_t, std::int32_t, float const *);
void glUniform3fv(std::int32_t, std::int32_t, float const *);
void glUniform4fv(std::int32_t, std::int32_t, float const *);
void glUniform1iv(std::int32_t, std::int32_t, std::int32_t const *);
void glUniform2iv(std::int32_t, std::int32_t, std::int32_t const *);
void glUniform3iv(std::int32_t, std::int32_t, std::int32_t const *);
void glUniform4iv(std::int32_t, std::int32_t, std::int32_t const *);
void glUniformMatrix2fv(std::int32_t, std::int32_t, std::uint8_t, float const *);
void glUniformMatrix3fv(std::int32_t, std::int32_t, std::uint8_t, float const *);
void glUniformMatrix4fv(std::int32_t, std::int32_t, std::uint8_t, float const *);
void glValidateProgram(std::uint32_t);
void glVertexAttrib1d(std::uint32_t, double);
void glVertexAttrib1dv(std::uint32_t, double const *);
void glVertexAttrib1f(std::uint32_t, float);
void glVertexAttrib1fv(std::uint32_t, float const *);
void glVertexAttrib1s(std::uint32_t, std::int16_t);
void glVertexAttrib1sv(std::uint32_t, std::int16_t const *);
void glVertexAttrib2d(std::uint32_t, double, double);
void glVertexAttrib2dv(std::uint32_t, double const *);
void glVertexAttrib2f(std::uint32_t, float, float);
void glVertexAttrib2fv(std::uint32_t, float const *);
void glVertexAttrib2s(std::uint32_t, std::int16_t, std::int16_t);
void glVertexAttrib2sv(std::uint32_t, std::int16_t const *);
void glVertexAttrib3d(std::uint32_t, double, double, double);
void glVertexAttrib3dv(std::uint32_t, double const *);
void glVertexAttrib3f(std::uint32_t, float, float, float);
void glVertexAttrib3fv(std::uint32_t, float const *);
void glVertexAttrib3s(std::uint32_t, std::int16_t, std::int16_t, std::int16_t);
void glVertexAttrib3sv(std::uint32_t, std::int16_t const *);
void glVertexAttrib4Nbv(std::uint32_t, std::int8_t const *);
void glVertexAttrib4Niv(std::uint32_t, std::int32_t const *);
void glVertexAttrib4Nsv(std::uint32_t, std::int16_t const *);
void glVertexAttrib4Nub(std::uint32_t, std::uint8_t, std::uint8_t, std::uint8_t, std::uint8_t);
void glVertexAttrib4Nubv(std::uint32_t, std::uint8_t const *);
void glVertexAttrib4Nuiv(std::uint32_t, std::uint32_t const *);
void glVertexAttrib4Nusv(std::uint32_t, std::uint16_t const *);
void glVertexAttrib4bv(std::uint32_t, std::int8_t const *);
void glVertexAttrib4d(std::uint32_t, double, double, double, double);
void glVertexAttrib4dv(std::uint32_t, double const *);
void glVertexAttrib4f(std::uint32_t, float, float, float, float);
void glVertexAttrib4fv(std::uint32_t, float const *);
void glVertexAttrib4iv(std::uint32_t, std::int32_t const *);
void glVertexAttrib4s(std::uint32_t, std::int16_t, std::int16_t, std::int16_t, std::int16_t);
void glVertexAttrib4sv(std::uint32_t, std::int16_t const *);
void glVertexAttrib4ubv(std::uint32_t, std::uint8_t const *);
void glVertexAttrib4uiv(std::uint32_t, std::uint32_t const *);
void glVertexAttrib4usv(std::uint32_t, std::uint16_t const *);
void glVertexAttribPointer(std::uint32_t, std::int32_t, std::uint32_t, std::uint8_t, std::int32_t, void const *);
void glUniformMatrix2x3fv(std::int32_t, std::int32_t, std::uint8_t, float const *);
void glUniformMatrix3x2fv(std::int32_t, std::int32_t, std::uint8_t, float const *);
void glUniformMatrix2x4fv(std::int32_t, std::int32_t, std::uint8_t, float const *);
void glUniformMatrix4x2fv(std::int32_t, std::int32_t, std::uint8_t, float const *);
void glUniformMatrix3x4fv(std::int32_t, std::int32_t, std::uint8_t, float const *);
void glUniformMatrix4x3fv(std::int32_t, std::int32_t, std::uint8_t, float const *);
void glColorMaski(std::uint32_t, std::uint8_t, std::uint8_t, std::uint8_t, std::uint8_t);
void glGetBooleani_v(std::uint32_t, std::uint32_t, std::uint8_t *);
void glGetIntegeri_v(std::uint32_t, std::uint32_t, std::int32_t *);
void glEnablei(std::uint32_t, std::uint32_t);
void glDisablei(std::uint32_t, std::uint32_t);
std::uint8_t glIsEnabledi(std::uint32_t, std::uint32_t);
void glBeginTransformFeedback(std::uint32_t);
void glEndTransformFeedback(void);
void glBindBufferRange(std::uint32_t, std::uint32_t, std::uint32_t, std::ptrdiff_t, std::ptrdiff_t);
void glBindBufferBase(std::uint32_t, std::uint32_t, std::uint32_t);
void glTransformFeedbackVaryings(std::uint32_t, std::int32_t, char const * *, std::uint32_t);
void glGetTransformFeedbackVarying(std::uint32_t, std::uint32_t, std::int32_t, std::int32_t *, std::int32_t *, std::uint32_t *, char *);
void glClampColor(std::uint32_t, std::uint32_t);
void glBeginConditionalRender(std::uint32_t, std::uint32_t);
void glEndConditionalRender(void);
void glVertexAttribIPointer(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, void const *);
void glGetVertexAttribIiv(std::uint32_t, std::uint32_t, std::int32_t *);
void glGetVertexAttribIuiv(std::uint32_t, std::uint32_t, std::uint32_t *);
void glVertexAttribI1i(std::uint32_t, std::int32_t);
void glVertexAttribI2i(std::uint32_t, std::int32_t, std::int32_t);
void glVertexAttribI3i(std::uint32_t, std::int32_t, std::int32_t, std::int32_t);
void glVertexAttribI4i(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glVertexAttribI1ui(std::uint32_t, std::uint32_t);
void glVertexAttribI2ui(std::uint32_t, std::uint32_t, std::uint32_t);
void glVertexAttribI3ui(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t);
void glVertexAttribI4ui(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t);
void glVertexAttribI1iv(std::uint32_t, std::int32_t const *);
void glVertexAttribI2iv(std::uint32_t, std::int32_t const *);
void glVertexAttribI3iv(std::uint32_t, std::int32_t const *);
void glVertexAttribI4iv(std::uint32_t, std::int32_t const *);
void glVertexAttribI1uiv(std::uint32_t, std::uint32_t const *);
void glVertexAttribI2uiv(std::uint32_t, std::uint32_t const *);
void glVertexAttribI3uiv(std::uint32_t, std::uint32_t const *);
void glVertexAttribI4uiv(std::uint32_t, std::uint32_t const *);
void glVertexAttribI4bv(std::uint32_t, std::int8_t const *);
void glVertexAttribI4sv(std::uint32_t, std::int16_t const *);
void glVertexAttribI4ubv(std::uint32_t, std::uint8_t const *);
void glVertexAttribI4usv(std::uint32_t, std::uint16_t const *);
void glGetUniformuiv(std::uint32_t, std::int32_t, std::uint32_t *);
void glBindFragDataLocation(std::uint32_t, std::uint32_t, char const *);
std::int32_t glGetFragDataLocation(std::uint32_t, char const *);
void glUniform1ui(std::int32_t, std::uint32_t);
void glUniform2ui(std::int32_t, std::uint32_t, std::uint32_t);
void glUniform3ui(std::int32_t, std::uint32_t, std::uint32_t, std::uint32_t);
void glUniform4ui(std::int32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t);
void glUniform1uiv(std::int32_t, std::int32_t, std::uint32_t const *);
void glUniform2uiv(std::int32_t, std::int32_t, std::uint32_t const *);
void glUniform3uiv(std::int32_t, std::int32_t, std::uint32_t const *);
void glUniform4uiv(std::int32_t, std::int32_t, std::uint32_t const *);
void glTexParameterIiv(std::uint32_t, std::uint32_t, std::int32_t const *);
void glTexParameterIuiv(std::uint32_t, std::uint32_t, std::uint32_t const *);
void glGetTexParameterIiv(std::uint32_t, std::uint32_t, std::int32_t *);
void glGetTexParameterIuiv(std::uint32_t, std::uint32_t, std::uint32_t *);
void glClearBufferiv(std::uint32_t, std::int32_t, std::int32_t const *);
void glClearBufferuiv(std::uint32_t, std::int32_t, std::uint32_t const *);
void glClearBufferfv(std::uint32_t, std::int32_t, float const *);
void glClearBufferfi(std::uint32_t, std::int32_t, float, std::int32_t);
std::uint8_t const * glGetStringi(std::uint32_t, std::uint32_t);
void glDrawArraysInstanced(std::uint32_t, std::int32_t, std::int32_t, std::int32_t);
void glDrawElementsInstanced(std::uint32_t, std::int32_t, std::uint32_t, void const *, std::int32_t);
void glTexBuffer(std::uint32_t, std::uint32_t, std::uint32_t);
void glPrimitiveRestartIndex(std::uint32_t);
void glGetInteger64i_v(std::uint32_t, std::uint32_t, std::int64_t *);
void glGetBufferParameteri64v(std::uint32_t, std::uint32_t, std::int64_t *);
void glFramebufferTexture(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t);
void glVertexAttribDivisor(std::uint32_t, std::uint32_t);
void glMinSampleShading(float);
void glBlendEquationi(std::uint32_t, std::uint32_t);
void glBlendEquationSeparatei(std::uint32_t, std::uint32_t, std::uint32_t);
void glBlendFunci(std::uint32_t, std::uint32_t, std::uint32_t);
void glBlendFuncSeparatei(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t);
std::uint8_t glIsRenderbuffer(std::uint32_t);
void glBindRenderbuffer(std::uint32_t, std::uint32_t);
void glDeleteRenderbuffers(std::int32_t, std::uint32_t const *);
void glGenRenderbuffers(std::int32_t, std::uint32_t *);
void glRenderbufferStorage(std::uint32_t, std::uint32_t, std::int32_t, std::int32_t);
void glGetRenderbufferParameteriv(std::uint32_t, std::uint32_t, std::int32_t *);
std::uint8_t glIsFramebuffer(std::uint32_t);
void glBindFramebuffer(std::uint32_t, std::uint32_t);
void glDeleteFramebuffers(std::int32_t, std::uint32_t const *);
void glGenFramebuffers(std::int32_t, std::uint32_t *);
std::uint32_t glCheckFramebufferStatus(std::uint32_t);
void glFramebufferTexture1D(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t);
void glFramebufferTexture2D(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t);
void glFramebufferTexture3D(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, std::int32_t);
void glFramebufferRenderbuffer(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t);
void glGetFramebufferAttachmentParameteriv(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t *);
void glGenerateMipmap(std::uint32_t);
void glBlitFramebuffer(std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::uint32_t);
void glRenderbufferStorageMultisample(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, std::int32_t);
void glFramebufferTextureLayer(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, std::int32_t);
void * glMapBufferRange(std::uint32_t, std::ptrdiff_t, std::ptrdiff_t, std::uint32_t);
void glFlushMappedBufferRange(std::uint32_t, std::ptrdiff_t, std::ptrdiff_t);
void glBindVertexArray(std::uint32_t);
void glDeleteVertexArrays(std::int32_t, std::uint32_t const *);
void glGenVertexArrays(std::int32_t, std::uint32_t *);
std::uint8_t glIsVertexArray(std::uint32_t);
void glGetUniformIndices(std::uint32_t, std::int32_t, char const * *, std::uint32_t *);
void glGetActiveUniformsiv(std::uint32_t, std::int32_t, std::uint32_t const *, std::uint32_t, std::int32_t *);
void glGetActiveUniformName(std::uint32_t, std::uint32_t, std::int32_t, std::int32_t *, char *);
std::uint32_t glGetUniformBlockIndex(std::uint32_t, char const *);
void glGetActiveUniformBlockiv(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t *);
void glGetActiveUniformBlockName(std::uint32_t, std::uint32_t, std::int32_t, std::int32_t *, char *);
void glUniformBlockBinding(std::uint32_t, std::uint32_t, std::uint32_t);
void glCopyBufferSubData(std::uint32_t, std::uint32_t, std::ptrdiff_t, std::ptrdiff_t, std::ptrdiff_t);
void glDrawElementsBaseVertex(std::uint32_t, std::int32_t, std::uint32_t, void const *, std::int32_t);
void glDrawRangeElementsBaseVertex(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, std::uint32_t, void const *, std::int32_t);
void glDrawElementsInstancedBaseVertex(std::uint32_t, std::int32_t, std::uint32_t, void const *, std::int32_t, std::int32_t);
void glMultiDrawElementsBaseVertex(std::uint32_t, std::int32_t const *, std::uint32_t, void const * *, std::int32_t, std::int32_t const *);
void glProvokingVertex(std::uint32_t);
GLsync glFenceSync(std::uint32_t, std::uint32_t);
std::uint8_t glIsSync(GLsync);
void glDeleteSync(GLsync);
std::uint32_t glClientWaitSync(GLsync, std::uint32_t, std::uint64_t);
void glWaitSync(GLsync, std::uint32_t, std::uint64_t);
void glGetInteger64v(std::uint32_t, std::int64_t *);
void glGetSynciv(GLsync, std::uint32_t, std::int32_t, std::int32_t *, std::int32_t *);
void glTexImage2DMultisample(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint8_t);
void glTexImage3DMultisample(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint8_t);
void glGetMultisamplefv(std::uint32_t, std::uint32_t, float *);
void glSampleMaski(std::uint32_t, std::uint32_t);
void glBlendEquationiARB(std::uint32_t, std::uint32_t);
void glBlendEquationSeparateiARB(std::uint32_t, std::uint32_t, std::uint32_t);
void glBlendFunciARB(std::uint32_t, std::uint32_t, std::uint32_t);
void glBlendFuncSeparateiARB(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t);
void glMinSampleShadingARB(float);
void glNamedStringARB(std::uint32_t, std::int32_t, char const *, std::int32_t, char const *);
void glDeleteNamedStringARB(std::int32_t, char const *);
void glCompileShaderIncludeARB(std::uint32_t, std::int32_t, char const * *, std::int32_t const *);
std::uint8_t glIsNamedStringARB(std::int32_t, char const *);
void glGetNamedStringARB(std::int32_t, char const *, std::int32_t, std::int32_t *, char *);
void glGetNamedStringivARB(std::int32_t, char const *, std::uint32_t, std::int32_t *);
void glBindFragDataLocationIndexed(std::uint32_t, std::uint32_t, std::uint32_t, char const *);
std::int32_t glGetFragDataIndex(std::uint32_t, char const *);
void glGenSamplers(std::int32_t, std::uint32_t *);
void glDeleteSamplers(std::int32_t, std::uint32_t const *);
std::uint8_t glIsSampler(std::uint32_t);
void glBindSampler(std::uint32_t, std::uint32_t);
void glSamplerParameteri(std::uint32_t, std::uint32_t, std::int32_t);
void glSamplerParameteriv(std::uint32_t, std::uint32_t, std::int32_t const *);
void glSamplerParameterf(std::uint32_t, std::uint32_t, float);
void glSamplerParameterfv(std::uint32_t, std::uint32_t, float const *);
void glSamplerParameterIiv(std::uint32_t, std::uint32_t, std::int32_t const *);
void glSamplerParameterIuiv(std::uint32_t, std::uint32_t, std::uint32_t const *);
void glGetSamplerParameteriv(std::uint32_t, std::uint32_t, std::int32_t *);
void glGetSamplerParameterIiv(std::uint32_t, std::uint32_t, std::int32_t *);
void glGetSamplerParameterfv(std::uint32_t, std::uint32_t, float *);
void glGetSamplerParameterIuiv(std::uint32_t, std::uint32_t, std::uint32_t *);
void glQueryCounter(std::uint32_t, std::uint32_t);
void glGetQueryObjecti64v(std::uint32_t, std::uint32_t, std::int64_t *);
void glGetQueryObjectui64v(std::uint32_t, std::uint32_t, std::uint64_t *);
void glDrawArraysIndirect(std::uint32_t, void const *);
void glDrawElementsIndirect(std::uint32_t, std::uint32_t, void const *);
void glUniform1d(std::int32_t, double);
void glUniform2d(std::int32_t, double, double);
void glUniform3d(std::int32_t, double, double, double);
void glUniform4d(std::int32_t, double, double, double, double);
void glUniform1dv(std::int32_t, std::int32_t, double const *);
void glUniform2dv(std::int32_t, std::int32_t, double const *);
void glUniform3dv(std::int32_t, std::int32_t, double const *);
void glUniform4dv(std::int32_t, std::int32_t, double const *);
void glUniformMatrix2dv(std::int32_t, std::int32_t, std::uint8_t, double const *);
void glUniformMatrix3dv(std::int32_t, std::int32_t, std::uint8_t, double const *);
void glUniformMatrix4dv(std::int32_t, std::int32_t, std::uint8_t, double const *);
void glUniformMatrix2x3dv(std::int32_t, std::int32_t, std::uint8_t, double const *);
void glUniformMatrix2x4dv(std::int32_t, std::int32_t, std::uint8_t, double const *);
void glUniformMatrix3x2dv(std::int32_t, std::int32_t, std::uint8_t, double const *);
void glUniformMatrix3x4dv(std::int32_t, std::int32_t, std::uint8_t, double const *);
void glUniformMatrix4x2dv(std::int32_t, std::int32_t, std::uint8_t, double const *);
void glUniformMatrix4x3dv(std::int32_t, std::int32_t, std::uint8_t, double const *);
void glGetUniformdv(std::uint32_t, std::int32_t, double *);
std::int32_t glGetSubroutineUniformLocation(std::uint32_t, std::uint32_t, char const *);
std::uint32_t glGetSubroutineIndex(std::uint32_t, std::uint32_t, char const *);
void glGetActiveSubroutineUniformiv(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t *);
void glGetActiveSubroutineUniformName(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, std::int32_t *, char *);
void glGetActiveSubroutineName(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, std::int32_t *, char *);
void glUniformSubroutinesuiv(std::uint32_t, std::int32_t, std::uint32_t const *);
void glGetUniformSubroutineuiv(std::uint32_t, std::int32_t, std::uint32_t *);
void glGetProgramStageiv(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t *);
void glPatchParameteri(std::uint32_t, std::int32_t);
void glPatchParameterfv(std::uint32_t, float const *);
void glBindTransformFeedback(std::uint32_t, std::uint32_t);
void glDeleteTransformFeedbacks(std::int32_t, std::uint32_t const *);
void glGenTransformFeedbacks(std::int32_t, std::uint32_t *);
std::uint8_t glIsTransformFeedback(std::uint32_t);
void glPauseTransformFeedback(void);
void glResumeTransformFeedback(void);
void glDrawTransformFeedback(std::uint32_t, std::uint32_t);
void glDrawTransformFeedbackStream(std::uint32_t, std::uint32_t, std::uint32_t);
void glBeginQueryIndexed(std::uint32_t, std::uint32_t, std::uint32_t);
void glEndQueryIndexed(std::uint32_t, std::uint32_t);
void glGetQueryIndexediv(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t *);
void glReleaseShaderCompiler(void);
void glShaderBinary(std::int32_t, std::uint32_t const *, std::uint32_t, void const *, std::int32_t);
void glGetShaderPrecisionFormat(std::uint32_t, std::uint32_t, std::int32_t *, std::int32_t *);
void glDepthRangef(float, float);
void glClearDepthf(float);
void glGetProgramBinary(std::uint32_t, std::int32_t, std::int32_t *, std::uint32_t *, void *);
void glProgramBinary(std::uint32_t, std::uint32_t, void const *, std::int32_t);
void glProgramParameteri(std::uint32_t, std::uint32_t, std::int32_t);
void glUseProgramStages(std::uint32_t, std::uint32_t, std::uint32_t);
void glActiveShaderProgram(std::uint32_t, std::uint32_t);
std::uint32_t glCreateShaderProgramv(std::uint32_t, std::int32_t, char const * *);
void glBindProgramPipeline(std::uint32_t);
void glDeleteProgramPipelines(std::int32_t, std::uint32_t const *);
void glGenProgramPipelines(std::int32_t, std::uint32_t *);
std::uint8_t glIsProgramPipeline(std::uint32_t);
void glGetProgramPipelineiv(std::uint32_t, std::uint32_t, std::int32_t *);
void glProgramUniform1i(std::uint32_t, std::int32_t, std::int32_t);
void glProgramUniform1iv(std::uint32_t, std::int32_t, std::int32_t, std::int32_t const *);
void glProgramUniform1f(std::uint32_t, std::int32_t, float);
void glProgramUniform1fv(std::uint32_t, std::int32_t, std::int32_t, float const *);
void glProgramUniform1d(std::uint32_t, std::int32_t, double);
void glProgramUniform1dv(std::uint32_t, std::int32_t, std::int32_t, double const *);
void glProgramUniform1ui(std::uint32_t, std::int32_t, std::uint32_t);
void glProgramUniform1uiv(std::uint32_t, std::int32_t, std::int32_t, std::uint32_t const *);
void glProgramUniform2i(std::uint32_t, std::int32_t, std::int32_t, std::int32_t);
void glProgramUniform2iv(std::uint32_t, std::int32_t, std::int32_t, std::int32_t const *);
void glProgramUniform2f(std::uint32_t, std::int32_t, float, float);
void glProgramUniform2fv(std::uint32_t, std::int32_t, std::int32_t, float const *);
void glProgramUniform2d(std::uint32_t, std::int32_t, double, double);
void glProgramUniform2dv(std::uint32_t, std::int32_t, std::int32_t, double const *);
void glProgramUniform2ui(std::uint32_t, std::int32_t, std::uint32_t, std::uint32_t);
void glProgramUniform2uiv(std::uint32_t, std::int32_t, std::int32_t, std::uint32_t const *);
void glProgramUniform3i(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glProgramUniform3iv(std::uint32_t, std::int32_t, std::int32_t, std::int32_t const *);
void glProgramUniform3f(std::uint32_t, std::int32_t, float, float, float);
void glProgramUniform3fv(std::uint32_t, std::int32_t, std::int32_t, float const *);
void glProgramUniform3d(std::uint32_t, std::int32_t, double, double, double);
void glProgramUniform3dv(std::uint32_t, std::int32_t, std::int32_t, double const *);
void glProgramUniform3ui(std::uint32_t, std::int32_t, std::uint32_t, std::uint32_t, std::uint32_t);
void glProgramUniform3uiv(std::uint32_t, std::int32_t, std::int32_t, std::uint32_t const *);
void glProgramUniform4i(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glProgramUniform4iv(std::uint32_t, std::int32_t, std::int32_t, std::int32_t const *);
void glProgramUniform4f(std::uint32_t, std::int32_t, float, float, float, float);
void glProgramUniform4fv(std::uint32_t, std::int32_t, std::int32_t, float const *);
void glProgramUniform4d(std::uint32_t, std::int32_t, double, double, double, double);
void glProgramUniform4dv(std::uint32_t, std::int32_t, std::int32_t, double const *);
void glProgramUniform4ui(std::uint32_t, std::int32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t);
void glProgramUniform4uiv(std::uint32_t, std::int32_t, std::int32_t, std::uint32_t const *);
void glProgramUniformMatrix2fv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, float const *);
void glProgramUniformMatrix3fv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, float const *);
void glProgramUniformMatrix4fv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, float const *);
void glProgramUniformMatrix2dv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, double const *);
void glProgramUniformMatrix3dv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, double const *);
void glProgramUniformMatrix4dv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, double const *);
void glProgramUniformMatrix2x3fv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, float const *);
void glProgramUniformMatrix3x2fv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, float const *);
void glProgramUniformMatrix2x4fv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, float const *);
void glProgramUniformMatrix4x2fv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, float const *);
void glProgramUniformMatrix3x4fv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, float const *);
void glProgramUniformMatrix4x3fv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, float const *);
void glProgramUniformMatrix2x3dv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, double const *);
void glProgramUniformMatrix3x2dv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, double const *);
void glProgramUniformMatrix2x4dv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, double const *);
void glProgramUniformMatrix4x2dv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, double const *);
void glProgramUniformMatrix3x4dv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, double const *);
void glProgramUniformMatrix4x3dv(std::uint32_t, std::int32_t, std::int32_t, std::uint8_t, double const *);
void glValidateProgramPipeline(std::uint32_t);
void glGetProgramPipelineInfoLog(std::uint32_t, std::int32_t, std::int32_t *, char *);
void glVertexAttribL1d(std::uint32_t, double);
void glVertexAttribL2d(std::uint32_t, double, double);
void glVertexAttribL3d(std::uint32_t, double, double, double);
void glVertexAttribL4d(std::uint32_t, double, double, double, double);
void glVertexAttribL1dv(std::uint32_t, double const *);
void glVertexAttribL2dv(std::uint32_t, double const *);
void glVertexAttribL3dv(std::uint32_t, double const *);
void glVertexAttribL4dv(std::uint32_t, double const *);
void glVertexAttribLPointer(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, void const *);
void glGetVertexAttribLdv(std::uint32_t, std::uint32_t, double *);
void glViewportArrayv(std::uint32_t, std::int32_t, float const *);
void glViewportIndexedf(std::uint32_t, float, float, float, float);
void glViewportIndexedfv(std::uint32_t, float const *);
void glScissorArrayv(std::uint32_t, std::int32_t, std::int32_t const *);
void glScissorIndexed(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t);
void glScissorIndexedv(std::uint32_t, std::int32_t const *);
void glDepthRangeArrayv(std::uint32_t, std::int32_t, double const *);
void glDepthRangeIndexed(std::uint32_t, double, double);
void glGetFloati_v(std::uint32_t, std::uint32_t, float *);
void glGetDoublei_v(std::uint32_t, std::uint32_t, double *);
GLsync glCreateSyncFromCLeventARB(struct _cl_context * context, struct _cl_event * event, std::uint32_t);
void glDebugMessageControlARB(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, std::uint32_t const *, std::uint8_t);
void glDebugMessageInsertARB(std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, char const *);
void glDebugMessageCallbackARB(GLDEBUGPROCARB callback, void const *);
std::uint32_t glGetDebugMessageLogARB(std::uint32_t, std::int32_t, std::uint32_t *, std::uint32_t *, std::uint32_t *, std::uint32_t *, std::int32_t *, char *);
std::uint32_t glGetGraphicsResetStatusARB(void);
void glGetnMapdvARB(std::uint32_t, std::uint32_t, std::int32_t, double *);
void glGetnMapfvARB(std::uint32_t, std::uint32_t, std::int32_t, float *);
void glGetnMapivARB(std::uint32_t, std::uint32_t, std::int32_t, std::int32_t *);
void glGetnPixelMapfvARB(std::uint32_t, std::int32_t, float *);
void glGetnPixelMapuivARB(std::uint32_t, std::int32_t, std::uint32_t *);
void glGetnPixelMapusvARB(std::uint32_t, std::int32_t, std::uint16_t *);
void glGetnPolygonStippleARB(std::int32_t, std::uint8_t *);
void glGetnColorTableARB(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, void *);
void glGetnConvolutionFilterARB(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, void *);
void glGetnSeparableFilterARB(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, void *, std::int32_t, void *, void *);
void glGetnHistogramARB(std::uint32_t, std::uint8_t, std::uint32_t, std::uint32_t, std::int32_t, void *);
void glGetnMinmaxARB(std::uint32_t, std::uint8_t, std::uint32_t, std::uint32_t, std::int32_t, void *);
void glGetnTexImageARB(std::uint32_t, std::int32_t, std::uint32_t, std::uint32_t, std::int32_t, void *);
void glReadnPixelsARB(std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t, std::uint32_t, std::int32_t, void *);
void glGetnCompressedTexImageARB(std::uint32_t, std::int32_t, std::int32_t, void *);
void glGetnUniformfvARB(std::uint32_t, std::int32_t, std::int32_t, float *);
void glGetnUniformivARB(std::uint32_t, std::int32_t, std::int32_t, std::int32_t *);
void glGetnUniformuivARB(std::uint32_t, std::int32_t, std::int32_t, std::uint32_t *);
void glGetnUniformdvARB(std::uint32_t, std::int32_t, std::int32_t, double *);
void glDrawArraysInstancedBaseInstance(std::uint32_t, std::int32_t, std::int32_t, std::int32_t, std::uint32_t);
void glDrawElementsInstancedBaseInstance(std::uint32_t, std::int32_t, std::uint32_t, const void *, std::int32_t, std::uint32_t);
void glDrawElementsInstancedBaseVertexBaseInstance(std::uint32_t, std::int32_t, std::uint32_t, const void *, std::int32_t, std::int32_t, std::uint32_t);
void glDrawTransformFeedbackInstanced(std::uint32_t, std::uint32_t, std::int32_t);
void glDrawTransformFeedbackStreamInstanced(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t);
void glGetInternalformativ(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, std::int32_t *);
void glGetActiveAtomicCounterBufferiv(std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t *);
void glBindImageTexture(std::uint32_t, std::uint32_t, std::int32_t, std::uint8_t, std::int32_t, std::uint32_t, std::uint32_t);
void glMemoryBarrier(std::uint32_t);
void glTexStorage1D(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t);
void glTexStorage2D(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, std::int32_t);
void glTexStorage3D(std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, std::int32_t, std::int32_t);
void glTextureStorage1DEXT(std::uint32_t, std::uint32_t, std::int32_t, std::uint32_t, std::int32_t);
void glTextureStorage2DEXT(std::uint32_t, std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, std::int32_t);
void glTextureStorage3DEXT(std::uint32_t, std::uint32_t, std::int32_t, std::uint32_t, std::int32_t, std::int32_t, std::int32_t);

}
}
}

using namespace Twil::Gl::Procs;
